#ifndef HN_PROPERTIES_H
#define HN_PROPERTIES_H

enum props{
	PROP_Fire_Resistance,
	PROP_Cold_Resistance,
	PROP_Sleep_Resistance,
	PROP_Disintegration_Resistance,
	PROP_Shock_Resistance,
	PROP_Acid_Resistance,
	PROP_Stone_Resistance,
	PROP_Poison_Resistance,

	PROP_Adorned,
	PROP_Regeneration,
	PROP_Searching,
	PROP_See_Invisible,
	PROP_Invisible,
	PROP_Teleport,
	PROP_Teleport_Control,
	PROP_Polymorph,
	PROP_Polymorph_Control,
	PROP_Levitation,
	PROP_Stealth,
	PROP_Aggravate_Monster,
	PROP_Conflict,
	PROP_Protection,
	PROP_Protection_From_Shape_Changers,
	PROP_Warning,
	PROP_Telepathy,
	PROP_Fast,
	PROP_Stunned,
	PROP_Confusion,
	PROP_Sick,
	PROP_Blinded,
	PROP_Sleeping,
	PROP_Wounded_Legs,
	PROP_Stoned,
	PROP_Strangled,
	PROP_Hallucination,
	PROP_Hallucination_Resistance,
	PROP_Fumbling,
	PROP_Jumping,
	PROP_Water_Walking,
	PROP_Hunger,
	PROP_Glib,
	PROP_Reflecting,
	PROP_Life_Saved,
	PROP_Antimagic,
	PROP_Displaced,
	PROP_Clairvoyant,
	PROP_Vomiting,
	PROP_Energy_Regeneration,
	PROP_Magical_Breathing,
	PROP_Half_SPDam,
	PROP_Half_PHDam,
	PROP_Sickness_Resistance,
	PROP_Drain_Resistance,
	PROP_Undead_Warning,
	PROP_Invulnerable,
	PROP_Free_Action,
	PROP_Swimming,
	PROP_Slimed,
	PROP_Fixed_Abilities,
	PROP_Flying,
	PROP_Unchanging,
	PROP_Passes_Walls,
	PROP_Slow_Digestion,
	PROP_Infravision,
	PROP_Warn_Of_Monsters,
	PROP_Detect_Monsters,
	
	PROP_Gain_Ability,
	PROP_Restore_Ability,
	PROP_Paralyse,
	PROP_Heal,
	PROP_Extra_Heal,
	PROP_Full_Heal,
	PROP_Gain_Level,
	PROP_Gain_Energy,
	PROP_Enlightenment,
	PROP_Detect_Objects,
	PROP_Sleep,
	PROP_Booze,
	PROP_Sickness,
	PROP_Juice,
	PROP_Oil,
	PROP_Acid,
	PROP_Water,
	
	PROP_MAX
};

#endif // HN_PROPERTIES_H
